### ISSUE TITLE
Option to read from stdin

### ISSUE THREAD

**Issue by lexual** [firecat53/tabview#118]
Would be good to be able to read from stdin, so I could use unix piping.

e.g.

    head -n 1000 my_big_data.csv | tabview --stdin

**Comment by firecat53** [comment]
Already exists :) (see tabview -h under filename). Just use '-' in place of the filename.

**Comment by lexual** [comment]
awesome, I did run --help, but missed it somehow, I think this probably makes my other feature request obsolete at least partly.

Looks like a really useful tool. Thanks ;)
