### ISSUE TITLE
1.4.1 version in pypi is missing files

### ISSUE THREAD

**Issue by wavexx** [firecat53/tabview#130]
As mentioned, I'm trying to make a Debian package out of tabview, and I've noticed that LICENSE.txt and CHANGELOG.rst are missing in the tarball uploaded to pypi.

These are mentioned in setup.py::data_files, so they're required when installing the package.

The download_url is also pointing to 1.4.0 (I would simply remove download_url here).

Could you fix these problems?
I'd rather point the Debian version to the one directly available in pypi for consistency.

**Comment by wavexx** [comment]
The sample files are missing as well (you cannot run the nose tests from there).

**Comment by firecat53** [comment]
Should be fixed now. Released 1.4.2 and uploaded to pypi. Let me know if I missed something!
