### ISSUE TITLE
Begin without a header if any cell in the first row is all digits

### ISSUE THREAD

**Issue by pjvandehaar** [firecat53/tabview#139]
ie,
```python
class Viewer:
    ...
    def __init__(self, *args, **kwargs):
        ...
        if len(self.data) > 1:
            del self.data[0]
            if any(cell.isdigit() for cell in data[0]):
                # Disable header because missing.
                self.header_offset = self.header_offset_orig - 1
            else:
                self.header_offset = self.header_offset_orig
        else:
            # Don't make one line file a header row
            self.header_offset = self.header_offset_orig - 1

        ...
```

**Comment by firecat53** [comment]
Can you please clarify what the intended purpose/use case for this is? I'm afraid I'm a little slow tonight :smile: Thanks.

**Comment by pjvandehaar** [comment]
By default, when I `tabview` a file, it makes the first row a header.  Most of my files don't have headers, so I hit `t` to remove the header.  I'd prefer if tabview would notice that a file doesn't have a header so that I wouldn't have to hit `t`.  I don't know a good way to check whether the first row is a header, but I know that if a cell in the first row is all digits, it's probably not a header.
