### ISSUE TITLE
Take input from stdin by default without requiring hyphen "-"

### ISSUE THREAD

**Issue by cirosantilli** [firecat53/tabview#141]
I want to write:

    printf 'a b\nc d\n' | tabview

instead of the currently required:

    printf 'a b\nc d\n' | tabview -

**Comment by firecat53** [comment]
Thanks for the request. However, I'd prefer to leave the '-' as the stdin indicator both for consistency with most other Unix tools (not all, I know) and to keep the interface consistent since the tool has been around for awhile and has a fair number of users already.
