### ISSUE TITLE
Behavior on resize when cell popup is shown

### ISSUE THREAD

**Issue by gurisko** [firecat53/tabview#38]
We should discuss what is the expected behavior of the show_cell window when we are resizing the terminal window. If we are going to implement #17 we should not close it because there can be unsaved changes. In this case we should also discuss window size and window placement.

**Comment by wavexx** [comment]
Yes, currently the cell popup might be truncated as well on narrow terminals.
What about doing something different, like drawing a divider at 50% of the terminal height and displaying the content at the bottom without border? This is what tig does when selecting a commit in the graph view (and mutt/etc/...)

**Comment by gurisko** [comment]
@wavexx I like that idea.

**Comment by firecat53** [comment]
Fixed crash on resize with Textbox popup open. 41c0f2721. I'm going to go ahead and close this issue. Any text editing issues that arise if we implement editing will be handled with that issue.
