### ISSUE TITLE
Numerical X/Y location

### ISSUE THREAD

**Issue by wavexx** [firecat53/tabview#44]
I really don't have any use for showing the column as a letter (spreadsheet like: A,B,C...).
On the other hand, whenever I need to use standard unix tools I always need the column number.
Making an option for this is easy, but some comments would be nice to have.

I would personally like an header like "  Y,X  " (which is pretty common for series-based datasets), and I would also love it to be the default with a switch to enable spreadsheet-like display.

What do others think?

**Comment by firecat53** [comment]
See my comments on #46
