### ISSUE TITLE
Feature Request: Variable width columns

### ISSUE THREAD

**Issue by firecat53** [firecat53/tabview#5]
Allow variable width columns. Set a maximum width and padding required, and if the column is less than the max width, reduce that column width. Would have to cycle through the list and find the max width for each column when first opening the file.

**Comment by firecat53** [comment]
> Remember to exclude the column label when calculating the width, as this is often unrelated.

So if you've got a column of mostly 2-5 digit numbers, but the column label is 15 characters, you'd rather have the column be 5 characters wide even though that would render the label not really readable?

I certainly see how that would make the data more readable. If you've got multiple skinny columns with labels all starting with the same 3-5 letters, will it be acceptable to not really be able to differentiate the column labels at a glance?

**Comment by wavexx** [comment]
On 01/07/2015 06:04 AM, Scott Hansen wrote:
>> Remember to exclude the column label when calculating the width, as
>> this is often unrelated.
> 
> So if you've got a column of mostly 2-5 digit numbers, but the column
> label is 15 characters, you'd rather have the column be 5 characters
> wide even though that would render the label not really readable?

Precisely.

> I certainly see how that would make the data more readable. If you've
> got multiple skinny columns with labels all starting with the same
> 3-5 letters, will it be acceptable to not really be able to
> differentiate the column labels at a glance?

It really depends, but for most of the time, yes.
Statisticians tend to shrink variable names a lot also for this reason.

I would rather have the column name (if any) in the info bar along with
the y position. If you have a row name, it would also make sense to have
a row/column name display. This could be a good alternative to a Y,X ->
index,column mode taken directly from the data.

In the end though, it's the data that counts. When you're working with
the same dataset over and over, you might only initially want to see the
labels. In this case it's fine to widen the columns manually.

But after that, you really stop caring.

This is also the reason why initially I proposed to implement the
column_size_up/down functions in terms of relative steps (+/-10%), so
that if you keep growing the size you get there much faster.

**Comment by jahrome** [comment]
+1, this would be a killer feature.

**Comment by jahrome** [comment]
First working implementation in https://github.com/firecat53/tabview/pull/82

**Comment by firecat53** [comment]
Test branch 'jahrome-variable_width_try2' (PR #85) with 'mode' based width calculations.

**Comment by firecat53** [comment]
Hey all. Sorry for the delay. A few more changes to the 'jahrome-variable_width_try2' branch.

- Working tests
- 'Mode' variable width is default (I'm open to discussion on this)
- Moved column width calculations from __init__ to it's own function(s)

I'd like to implement a key binding to switch column width modes, but I don't think we need to do that before this branch goes into master.

Thanks!
