### ISSUE TITLE
Add python2 support

### ISSUE THREAD

**Issue by firecat53** [firecat53/tabview#51]
Initial python 2.x support is in the 'python2' branch. It runs, but there there seems to be an error somewhere in figuring out the gap and/or column width.

**Comment by wavexx** [comment]
Seems to work for me on 2.7. Do you have a specific example?
Though you need to add:

    # -*- coding: utf-8 -*-

as the first line in tabview/tabview.py in order to use utf-8 literals (as we use "…" as the default truncation indicator).

**Comment by firecat53** [comment]
Hopefully this test csv doesn't get too mangled. The gap is wrong after the truncated lines.

	"sku","product-id","product-id-type","product-name","brand"
	"01908E1",,,"Alternative Ladies' Lakeside Dress 01908E1","Alternative"
	"01908E1-ALTERNECOBLACKL118004","667558180044","UPC","Alternative Ladies' Lakeside Dress>L ECO BLACK 01908E1","Alternative"
	"01908E1-ALTERNECOBLACKM118003","667558180037","UPC","Alternative Ladies' Lakeside Dress>M ECO BLACK 01908E1","Alternative"
	"01908E1-ALTERNECOBLACKS118002","667558180020","UPC","Alternative Ladies' Lakeside Dress>S ECO BLACK 01908E1","Alternative"
	"01908E1-ALTERNECOBLACKXL118005","667558180051","UPC","Alternative Ladies' Lakeside Dress>XL ECO BLACK 01908E1","Alternative"

**Comment by wavexx** [comment]
On 01/03/2015 08:29 PM, Scott Hansen wrote:
> Hopefully this test csv doesn't get too mangled. The gap is wrong
> after the truncated lines.

Looks like it detects the wrong encoding, writing something that looks
like double-width characters.

If you specify manually --encoding=utf-8 the display is fine, but the
data is handled incorrectly.

**Comment by firecat53** [comment]
Changing the truncation character to something like '>' does "fix" it. Not a long-term solution, though.

We need some unicode heavy CSV's to test with I think.

**Comment by wavexx** [comment]
On 01/03/2015 09:10 PM, Scott Hansen wrote:
> Changing the truncation character to something like '>' does "fix"
> it. Not a long-term solution, though.

I've been using utf8 literals in the past with curses and python 2.7,
and I didn't remember such issues.

Since '...' is rendered correctly I suspect there's a charset conversion
going on. I didn't understand fully how you use 'csv' to read the file,
but it would be nice to inspect the type/encoding of the items being parsed.

**Comment by firecat53** [comment]
The problem was incorrectly calculating the length of the trunc_char string. If we just assume it will be a single character, then the problem is easily solved.

However...this file fails miserably:
http://www.i18nguy.com/unicode/unicode-example-utf8.zip

It works with python 3, but there are still a lot of artifacts. Opening a separate issue for that.

**Comment by firecat53** [comment]
Fixed by #60.
