### ISSUE TITLE
Improve Unicode support

### ISSUE THREAD

**Issue by firecat53** [firecat53/tabview#54]
This file opens, but has some visual artifacts and inconsistent formatting:

http://www.i18nguy.com/unicode/unicode-example-utf8.zip

Edit: fails completely with python 2.x

**Comment by wavexx** [comment]
This should be fixed now.

**Comment by firecat53** [comment]
Some of the Asian languages use a double-wide character that messes with terminal formatting that assumes each character is a single (this is obvious from the unicode test file I linked). I briefly looked into this and the only way I could see to 'fix' it would be to go through the entire file and use the 'unicodedata.east_asian_width' to figure it out for every cell. That seems slow for any significant sized file, but I haven't tried it yet.

Other ideas? Or is it not worth fixing yet?

**Comment by wavexx** [comment]
On 01/09/2015 05:03 PM, Scott Hansen wrote:
> Some of the Asian languages use a double-wide character that messes
> with terminal formatting that assumes each character is a single
> (this is obvious from the unicode test file I linked). I briefly
> looked into this and the only way I could see to 'fix' it would be to
> go through the entire file and use the 'unicodedata.east_asian_width'
> to figure it out for every cell. That seems slow for any significant
> sized file, but I haven't tried it yet.

You could support those by changing only padstr().
But is east_asian_width really the correct way to do it?

> Other ideas? Or is it not worth fixing yet?

It would be nice to know if the string contains at least one of those
characters, to turn on wide-character processing. This would have
minimal impact on performance if implemented conditionally in padstr().

Though I see no other way of calling east_asian_width on each character
to know this beforehand...

**Comment by wavexx** [comment]
On 01/09/2015 05:44 PM, Yuri D'Elia wrote:
> You could support those by changing only padstr().
> But is east_asian_width really the correct way to do it?

Huh, not really. There is a bad interaction between cursor movement and
double-width characters that breaks display().

See my double_width_chars branch for a test.

**Comment by wavexx** [comment]
On 01/09/2015 07:04 PM, Yuri D'Elia wrote:
> Huh, not really. There is a bad interaction between cursor movement and
> double-width characters that breaks display().
> 
> See my double_width_chars branch for a test.

It seems that insstr() is inconsistent in how it shifts the characters,
leading to unaligned columns.

IMHO there's an inner problem in how curses *itself* switches the
terminal between wide-char and regular mode (printing a regular-width
char instead of spaces would fix the issue as well, which is telling!),
but I gave up understanding.

I changed back the code to only use addstr(), and it works correctly.

The trouble is that we lose the bottom-rightmost character.

If we shifted the info bar at the bottom (instead of the top), it would
make handling easier, as we would truncate the info bar only without
doing exceptions in the regular drawing call.

I would recommend doing this.

**Comment by firecat53** [comment]
I just discovered this project by accident: https://github.com/jquast/wcwidth

I haven't had time to check out what you've done yet, but thought it might be relevant.

**Comment by firecat53** [comment]
I personally prefer the info bar at the top. I did try it out at the bottom just to see :smile: 

However, I was able to use the insstr for the bottom right cell instead of addstr and that prevented missing out on that lower right character. With an asian-language heavy file, there was a tiny bit of visual disturbance in that lower right corner when scrolling, but it seemed minor and is likely to be a rare occurrence.

**Comment by wavexx** [comment]
On 02/05/2015 05:21 PM, Scott Hansen wrote:
> However, I was able to use the insstr for the bottom right cell
> instead of addstr and that prevented missing out on that lower right
> character. With an asian-language heavy file, there was a tiny bit of
> visual disturbance in that lower right corner when scrolling, but it
> seemed minor and is likely to be a rare occurrence.

I'd like to see that, did you push it already so I can try?

**Comment by firecat53** [comment]
Yes, it's in the wavexx-double_width_characters branch.

**Comment by wavexx** [comment]
On 02/05/2015 05:21 PM, Scott Hansen wrote:
> However, I was able to use the insstr for the bottom right cell
> instead of addstr and that prevented missing out on that lower right
> character. With an asian-language heavy file, there was a tiny bit of
> visual disturbance in that lower right corner when scrolling, but it
> seemed minor and is likely to be a rare occurrence.

Seems reasonable. I cannot think of anything better right now for what
seems to be a curses repositioning bug...
