### ISSUE TITLE
Starting line/column

### ISSUE THREAD

**Issue by wavexx** [firecat53/tabview#55]
It would be nice to support the classical ``+line[:col]`` flag as typically done by editors to set the initial cursor position.

**Comment by firecat53** [comment]
On Sun, Jan 04, 2015 at 03:55:23PM -0800, wavexx wrote:
>    It would be nice to support the classical +line[:col] flag as typically
>    done by editors to set the initial cursor position.

Are you talking command line switch? Like:

    tabview +25:4 <filename>

Is it worth the extra code given we've already got quick goto row and column
commands?

**Comment by wavexx** [comment]
On 01/05/2015 01:02 AM, Scott Hansen wrote:
> On Sun, Jan 04, 2015 at 03:55:23PM -0800, wavexx wrote:
>>    It would be nice to support the classical +line[:col] flag as typically
>>    done by editors to set the initial cursor position.
> 
> Are you talking command line switch? Like:
> 
>     tabview +25:4 <filename>
> 
> Is it worth the extra code given we've already got quick goto row and column
> commands?

Imagine using tabview for showing a data error in a table automatically
(hint: I'm doing nothing of the sorts ;)).

Just pop the viewer at the right spot.

**Comment by firecat53** [comment]
I think I've got this working. 'start_pos' branch. Command line switch:

    tabview --start_pos 2 <fn>   OR   tabview -yx 4,5 <fn>

Also as a parameter (tuple or integer):

     tabview.view(data=xxx, start_pos=(5,4))

Let me know if that works as you had intended.

**Comment by wavexx** [comment]
On 01/18/2015 05:47 PM, Scott Hansen wrote:
> I think I've got this working. 'start_pos' branch. Command line switch:
> 
>     tabview --start_pos 2 <fn>   OR   tabview -yx 4,5 <fn>

I'd rather have a +Y[:X] switch, given how consistently has been
implemented in various editors.

I'm not sure how to implement this in argparse though.

**Comment by firecat53** [comment]
Give it a try now. I added that as an option to the 'normal' python argparse --start_pos.

**Comment by scls19fr** [comment]
Ok

I try both

    python bin/tabview sample/data_ohlcv.csv +3:5

and 

   python bin/tabview sample/data_ohlcv.csv --start_pos 3,5

it seems ok but you might be less restrictive allowing for example

    python bin/tabview sample/data_ohlcv.csv +:5

but it raises

    Traceback (most recent call last):
      File "bin/tabview", line 56, in <module>
        start_pos = (int(sp[0]), int(sp[1]))
    ValueError: invalid literal for int() with base 10: ''

maybe 

    try:
        row = int(sp[0])
    except:
        row = 1

and same for col (1)

same approach with

    python bin/tabview sample/data_ohlcv.csv --start_pos ,5

it raises

    Traceback (most recent call last):
      File "bin/tabview", line 52, in <module>
        start_pos = [int(i) for i in start_pos]
    ValueError: invalid literal for int() with base 10: '

same idea...

**Comment by firecat53** [comment]
Fixed and closed with the last 3 commits.
