### ISSUE TITLE
Display number of lines and number of columns

### ISSUE THREAD

**Issue by scls19fr** [firecat53/tabview#58]
Hello,

it will be nice to display number of lines and number of columns.
so instead of "C-7" for cell position we could have
3/10 - 7/100

Kind regards

**Comment by wavexx** [comment]
On 01/05/2015 04:48 PM, scls19fr wrote:
> Hello,
> 
> it will be nice to display number of lines and number of columns.
> so instead of "C-7" for cell position we could have
> 3/10 - 7/100

This has also been done already in the master branch.

**Comment by firecat53** [comment]
Not quite... We don't have the totals in there yet.

**Comment by wavexx** [comment]
On 01/05/2015 06:26 PM, Scott Hansen wrote:
> Not quite... We don't have the totals in there yet.

Ok, I didn't catch this in the description.

**Comment by firecat53** [comment]
Ok guys...simple fix but I want to make sure it looks ok and doesn't clutter the display too much. Checkout the 'num_lines_columns' branch.

Another option I considered is having an info shortcut (like ^g in 'less') that pops up the filename, file size and total rows/columns.

Scott

**Comment by wavexx** [comment]
On 01/06/2015 04:47 AM, Scott Hansen wrote:
> Ok guys...simple fix but I want to make sure it looks ok and doesn't
> clutter the display too much. Checkout the 'num_lines_columns'
> branch.

Feels a bit odd the way is formatted. But maybe I'm just not used to
this format.

@scl19fr: what do you think?

One thing, I would add a second space just after the position (just to
have a consistent padding with the cursor info). I think I've put one
last time, but 2 would feel more consistent.

> Another option I considered is having an info shortcut (like ^g in
> 'less') that pops up the filename, file size and total rows/columns.

That would be a very nice addition.
Filename might now always there though.

In fact, when used as a module, I could clearly think that the user
might want to add some info to the dataset being displayed.

An extra parameter to view(...info="...") which defaults to the filename
might be a good thing. See:

https://github.com/firecat53/tabview/pull/59#issuecomment-68800330

**Comment by wavexx** [comment]
Also... do we really want to support irregular data?
Because if we do, we need to fix cursor handling in a few places...
In the other case, we need to widen short columns in the initialization to make the code uniform.
I would do the latter.

**Comment by firecat53** [comment]
> Also... do we really want to support irregular data?
> Because if we do, we need to fix cursor handling in a few places...
> In the other case, we need to widen short columns in the initialization to make the code uniform.
> I would do the latter.

Umm...is this supposed to be in a different issue? I don't understand the context here :)

**Comment by wavexx** [comment]
On 01/07/2015 03:33 AM, Scott Hansen wrote:
>> Also... do we really want to support irregular data? Because if we
>> do, we need to fix cursor handling in a few places... In the other
>> case, we need to widen short columns in the initialization to make
>> the code uniform. I would do the latter.
> 
> Umm...is this supposed to be in a different issue? I don't understand
> the context here :)

Probably yes, it should be a new issue.

I would just widen all columns when we read-in the file, so that we can
assume a matrix. It would simplify code here and there, and I think it
would also be more logical for the user.

**Comment by firecat53** [comment]
FYI, I'm going to implement this as part of an 'info' block that can be opened that has a list of:

- file name/data 'info' string
- file size
- current position (y,x) and (row label, column label)
- total rows/columns

**Comment by scls19fr** [comment]
Hi,

I just wonder if you want to remove current position from always viewable screen ?

row label and column label is a great idea but don't forget that you can have a Multindex as row or column !
Maybe freeze pane will be the first feature to provide because row label and column label could be find according what rows / columns are frozen !

Kind regards

**Comment by wavexx** [comment]
On 02/04/2015 06:44 AM, scls19fr wrote:
> Hi,
> 
> I just wonder if you want to remove current position from always
> viewable screen ?
> 
> row label and column label is a great idea but don't forget that you
> can have a Multindex as row or column ! Maybe freeze pane will be the
> first feature to provide because row label and column label could be
> find according what rows / columns are frozen !

>1 indexes would be nice to support, but it's tricky to setup without
starting from a data structure that exposes the index in the first
place. Tabular files don't give you much in this sense.

I'm still thinking about a way to correctly integrate a tabular viewer
into pandas for this, especially because I'm working with larger and
larger data sets where it would make sense to base the viewer directly
on the DataFrame as opposed to do a transform beforehand.
