### ISSUE TITLE
Shorter command line help

### ISSUE THREAD

**Issue by wavexx** [firecat53/tabview#63]
The current command line help is overwhelming. We should take the time to move most of the commentary to a simple man page instead.

**Comment by gurisko** [comment]
It would also be handy to add a footer with some useful commands.
Additionally - why aren't we using any Ctrl combinations?

**Comment by firecat53** [comment]
> It would also be handy to add a footer with some useful commands.

I'm more a fan of a pop-up hidden help screen (gmail style). In my opinion, a permanent help bar makes the display too busy, especially for a terminal app. 

> Additionally - why aren't we using any Ctrl combinations?

Because I'm a Vim user! :smile: Seriously though , I'm trying to keep this viewer as simple as possible. We haven't run out of single key commands yet...

**Comment by wavexx** [comment]
On 02/04/2015 03:35 PM, Scott Hansen wrote:
>> It would also be handy to add a footer with some useful commands.
> 
> I'm more a fan of a pop-up hidden help screen (gmail style). In my
> opinion, a permanent help bar makes the display too busy, especially
> for a terminal app.

The help/status bar (and menus, and scrollbars... (and animations -- the
new fad)) is the first thing I disable in almost every software I
stumble upon.

>> Additionally - why aren't we using any Ctrl combinations?
> 
> Because I'm a Vim user! :smile: Seriously though , I'm trying to keep
> this viewer as simple as possible. We haven't run out of single key
> commands yet...

I would be open to this (we could just support simple control
combinations), but I don't have many that I can think of.

C-a/C-e for 0/$, and also C-s/C-r for search forward/backward.

These are pretty common emacs-like bindings that are supported almost
everywhere for line editing.

No harm in putting these into the handler table.
