### ISSUE TITLE
Support reading from stdin

### ISSUE THREAD

**Issue by wavexx** [firecat53/tabview#79]
I would love to support the following:

    data-producing-command | tabview -

This requires some changes in the input parsing so that the file is never opened more than once (which is a good thing anyway, as the current code would break if the file is changed between detect_encoding/sniff/actual reading).

**Comment by firecat53** [comment]
I have some code in my urlscan project that might be reusable for this. Or
at least a place to start.

**Comment by jahrome** [comment]
Hi, this enhancement would be great !
