### ISSUE TITLE
"Reload" resets too much

### ISSUE THREAD

**Issue by wavexx** [firecat53/tabview#90]
I noticed that the column_gap gets reset when reloading a file.
Similarly, the status of the header_offset is also reset.

If I'm working on the same data file and I reload, I expect as much as the previous environment to be preserved, including most visual settings, position (it possible), and also previous search pattern (if any). Even column widths, probably! I'd rather have a "reset column widths" binding for that purpose.

This is obviously a side effect of how reload is implemented, which is pretty trivial right now. However, it's not convenient for the user.

**Comment by wavexx** [comment]
I should add that since "reload" is triggered when changing the column width mode ('c'), this is definitely annoying.

**Comment by firecat53** [comment]
Working on a fix for changing the column width mode without a reload...that was annoying!

My thought was that a reload is just resetting all the settings to the defaults that we started with. More of a refresh. The current reload doesn't actually re-read a file. Was that your intention?

**Comment by firecat53** [comment]
Easy fix for column width mode change.

I'm strongly considering changing the default column width mode to a fixed width like 20. It's a good 2 seconds faster on initial startup using a fixed width with an ~35MB file. Thoughts?

**Comment by wavexx** [comment]
On 02/02/2015 08:37 PM, Scott Hansen wrote:
> Easy fix for column width mode change.
> 
> I'm strongly considering changing the default column width mode to a fixed width like 20. It's a good 2 seconds faster on initial startup using a fixed width with an ~35MB file. Thoughts?

I don't mind.

**Comment by wavexx** [comment]
On 02/02/2015 08:16 PM, Scott Hansen wrote:
> My thought was that a reload is just resetting all the settings to
> the defaults that we started with. More of a refresh. The current
> reload doesn't actually re-read a file. Was that your intention?

I'm not sure I follow (I didn't actually notice if the file was reloaded
or not, but I did notice there was a screen cleanup while changing the
column mode).

'r' should definitely reload the file, but shouldn't attempt to change
any other setting IMHO.

If I change the column_gap to 5 char and tab mode to fixed-20 char, and
I reload because I want to see the updated file (which is probably
growing), I don't want reload to trash my current settings. I don't even
want my cursor to be moved, because probably I'm at the end of the file
and want to see the new rows.

**Comment by firecat53** [comment]
I think it's good to go. Column widths and mode, column gap, and search string are all retained between file reloads.

Same branch 'toggle_col_width_fix'. Please test and let me know if it works right!
